# docs: https://grafana.com/docs/grafana/latest/installation/docker/
# dockerfile: https://github.com/grafana/grafana/blob/main/Dockerfile
# dockerhub: https://hub.docker.com/r/grafana/grafana
# mysql not connected by Grafana by default

version: '3.8'

services:

  grafana:
    image: grafana/grafana:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}  
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${APP_PORT}:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
      # if you want to bind mount below, run command `chown -R grafana volumes/grafana`
      #- ./volumes/grafana/logs:/var/log/grafana
    environment:
      # You can add plugin verion like this grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5
      # You can install plugin from URL like this http://plugin-domain.com/my-custom-plugin.zip;custom-plugin,grafana-clock-panel
      # You can use any environment from grafana.ini. format: GF_[group]_item
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_LOG_MODE=console file
      - GF_SECURITY_ADMIN_USER=${APP_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${APP_PASSWORD}

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_CONTAINER_NAME}-mysql
    restart: always
    stdin_open: true
    tty: true
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_config/conf.d:/etc/mysql/conf.d
      - ${VOLUMES_PATH_PREFIX}/mysql/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  grafana_data:
  grafana_config: