# this file from docker-compose.workspace, delete mail-server
# default MySQL root password is 123456

# docs: https://grafana.com/docs/grafana/latest/installation/docker/
# dockerfile: https://github.com/grafana/grafana/blob/main/Dockerfile
# dockerhub: https://hub.docker.com/r/grafana/grafana

version: '3.8'

services:

  grafana:
    image: grafana/grafana:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}  
    restart: always
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./volumes/grafana-data:/var/lib/grafana
      - ./volumes/grafana-provisioning/:/etc/grafana/provisioning
    environment:
      # You can add plugin verion like this "grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5"
      # You can install plugin from URL like this "http://plugin-domain.com/my-custom-plugin.zip;custom-plugin,grafana-clock-panel"
      - GF_INSTALL_PLUGINS="grafana-clock-panel,grafana-simple-json-datasource"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    user: root

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  grafana: